version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tldb
      POSTGRES_USER: tluser
      POSTGRES_PASSWORD: tlpassword
